### PR TITLE
#48 fix

### LINKED ISSUE #48: User avatar image not available after leaving Discord server
🐛 Bug Description
When a user leaves the Discord server, their avatar image becomes unavailable or shows as "image doesn't exist", causing display issues in bot features that reference the user's avatar.

### PR DESCRIPTION
**Pull request by ashkuan**
When a user leaves the Discord server, calling displayAvatarURL() on a non-existent user object causes errors or returns invalid URLs, preventing the UI from displaying a proper fallback (gray placeholder avatar).Return empty string for non-existent users to trigger gray placeholder generation

#48

### CODE REVIEW

File: src/utils/getTeamMembers.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ module.exports = async function getTeamMembersInfo(userIds, guild) {
       return {
         userId: id,
         name: member.displayName || member.user.username || "Unknown",
-        avatar: member.displayAvatarURL({ extension: "png", size: 64 }),
+        avatar: member.displayAvatarURL({ extension: "png", size: 64 }) || "",
```
Comment (Ian-I-Chien) [inline src/utils/getTeamMembers.js:28]: Is it supposed to be
`avatar: member?.displayAvatarURL({ extension: "png", size: 64 }) || "",` ?

**Review by Ian-I-Chien — CHANGES_REQUESTED** [review]
